matrix:
  include:
    - os: osx
      osx_image: xcode11.5

    - os: linux
      dist: bionic

    - os: windows

language: sh

# cache:
#   directories:
#     - $HOME/texlive
#     - $HOME/.texlive
#     - $HOME/texmf

install:
  - . ./install-tex.sh

script:
  - latex -v
  - tlmgr --version
  - ./tlmgr.sh install collection-langjapanese
  - platex -v
